### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by pierceray** [wellington/wellington-bin#3]
I wanted to bump the version of Wellington being installed with grunt-wellington, but I'm not sure what versioning scheme to use with the package.json and the wellington version.  Some clarification around that would be helpful.

**Comment by andystalick** [comment]
The versioning scheme is de-linked with wellington so that we can push fixes to this repo. Wellington's version is defined in the package.json as wtVersion. So I think we'd increment the minor number every time we update the wellington version per semver.org's description, 
`MINOR version when you add functionality in a backwards-compatible manner`

**Comment by drewwells** [comment]
`npm version minor` will do all the magic and tag the git repo
